# Generated by Django 5.2.1 on 2025-05-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diaryentries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('encrypted_text', models.BinaryField(blank=True, null=True)),
                ('iv', models.BinaryField(blank=True, null=True)),
                ('auth_tag', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diaryentries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmotionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('analyzed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'emotion_analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'emotions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EncryptionKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_version', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'encryption_keys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyReports',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'yyyy_mm', blank=True, editable=False, primary_key=True, serialize=False)),
                ('yyyy_mm', models.CharField(max_length=7)),
                ('match_count', models.IntegerField()),
                ('total_count', models.IntegerField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'monthly_reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('birthday_year', models.IntegerField()),
                ('birthday_month', models.IntegerField()),
                ('birthday_day', models.IntegerField()),
                ('email', models.TextField()),
                ('gender', models.TextField()),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
